name: CICD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

    
jobs:
 
  depoly:
    runs-on: ubuntu-latest

    steps:
     - name: SSH deploy
       uses: appleboy/ssh-action@master
       with:
          host: ${{ secrets.HOST }}
          username:  ${{ secrets.USER }}
          key:  ${{ secrets.KEY }}
          port:  ${{ secrets.PORT }}
          script: |
               cd /home/ubuntu/Mintavibe-Backend
               git pull origin main
               npm install
               npm run build
